### ISSUE TITLE
Properties[] and Required[] keywords do not have a value?

### ISSUE THREAD

**Issue by ronaldwanink** [ovac/idoc#29]
In no way I seem to be able to make idoc generate values for Properties and Required keywords in the schema of the @response content. Any indication how to do this?

**Comment by ovac** [comment]
Here's an example:

/**
     * Store item
     *
     * Add a new item to the items collection.
     *
     * @bodyParam name string required
     * The name of the item. Example: Samsung Galaxy s10
     *
     * @bodyParam price number required
     * The price of the item. Example: 100.00
     *
     * @authenticated
     * @response {
     *      "status": 200,
     *      "success": true,
     *      "data": {
     *          "id": 10,
     *          "price": 100.00,
     *          "name": "Samsung Galaxy s10"
     *      }
     * }
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
