### ISSUE TITLE
How to fix not correct when show multiple respones status code.

### ISSUE THREAD

**Issue by ittranvantruong** [ovac/idoc#35]
/**
 * Example API method with multiple responses.
 *
 * @response 200 {
 *     "success": true,
 *     "message": "Operation completed successfully."
 * }
 * @response 400 {
 *     "success": false,
 *     "message": "Bad request."
 * }
 * @response 401 {
 *     "success": false,
 *     "message": "Unauthorized."
 * }
 *
 * @return \Illuminate\Http\Response
 */
Here, there are four respone status code. But i when render code has only response status 200. Can you help me fix?

**Comment by ovac** [comment]
Remove the 200. When there's no error code, it assumes success and checks for other error codes.

**Comment by ovac** [comment]
Feel free to reopen this issue if you still face same issues.

**Comment by leon-mrks** [comment]
+1
The docs don't show any stated error responses. No matter if the 200 status code is supplied or not (or any positive response).
