### ISSUE TITLE
Request - Config adjust to provide a custom documentation.blade file

### ISSUE THREAD

**Issue by avido** [ovac/idoc#6]
Would be nice to be able to provide a custom documentation.blade file to be able to change the RedocPro.init() configuration

**Comment by ovac** [comment]
In order to have this, you can publish the blade file like so: 

`php artisan vendor:publish --tag=idoc-views`

After that, the view file will be copied to `resources/views/vendor/idoc/documentation.blade.php`

**Comment by avido** [comment]
Ah Nice !..

Tnxx for the update.

Not the right place but small question tough. 
Is it possible to define a response type + layout in the docblock ? 
And are you going to implement the @apiResourceCollection notations ?

**Comment by qodehub-victor** [comment]
I may consider this in the next major release
